mer:
	latexmk -pdf mer.tex
	latexmk -c
	convert -density 300 mer.pdf mer.jpg

tabelas:
	latexmk -pdf tabelas.tex
	latexmk -c
	convert -density 300 tabelas.pdf tabelas.jpg

tables:
	latexmk -pdf tables.tex
	latexmk -c
	convert -density 300 tables.pdf tables.jpg
	